### ISSUE TITLE
Tripal 3 ready?

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal_analysis_go#11]
It's me again!
Is this module ready for Tripal 3 ? I can load data, but I can't see the data displayed anywhere, and there are no field definitions, did I miss something?

**Comment by bradfordcondon** [comment]
hi @abretaud 
the importer of this module functions, so you can load in GO annotations for features (assuming you didnt load them at the interpro annotation step).

To the best of my knowledge the GO page that displays a chart of annotations works  (but the site i worked on didnt use it).  --- https://github.com/tripal/tripal_analysis_go/blob/7.x-3.x/includes/tripal_analysis_go.chart.inc

Said chart should probably be made available as a field attached to organism and analysis.  What do you think, would you like this feature?

I dont know that a field is necessary for feature, since the annotations show up with or without this modules help.

finally I'll plug that we use tripal_cv_xray to make a browseable annotation chart on a per organism level. https://github.com/statonlab/tripal_cv_xray
meaning you can browse the GO CV and see that there are X genes associated with this term (and all of its children) terms.

 
![image](https://user-images.githubusercontent.com/7063154/46421753-d3138780-c700-11e8-8385-fcfc061bf678.png)

**Comment by bradfordcondon** [comment]
@spficklin would be good to get your input too.

**Comment by abretaud** [comment]
> Said chart should probably be made available as a field attached to organism and analysis. What do you think, would you like this feature?

This would be great yes! Are you proposing to do it? ;)

I didn't know https://github.com/statonlab/tripal_cv_xray, it looks cool! The tripal_analysis_go chart includes a tree of GO similar to your screenshot, but you can't get the list of features tagged with a given GO term. Maybe I'll use tripal_cv_xray someday, I have to think about it

**Comment by bradfordcondon** [comment]
>Are you proposing to do it? ;)

Sadly I am not as I just don't have any reason/investment to do so.  But I'd definitely welcome a submission.  I personally think the CV_Xray approach provides much more value (and I have a personal vendetta against GO-based pie-charts :P)  but it brings some admin upkeep with it (defining the indexes and populating them) that make it its own module for sure.

**Comment by bradfordcondon** [comment]
@mboudet has generously ported this functionality in #12 . Thank you!
